### ISSUE TITLE
Allow password authentication

### ISSUE THREAD

**Issue by iamhectorsosa** [arshad-yaseen/markdx#13]
Hey, Arshad.

Been using MarkDX here and there and I really enjoy it as a writing experience. Have an issue with not having password authentication. I'm trying to use this in my iPad and links from email open in a temporary window. The sign is successful but the session isn't persisted in the browser once it is closed.

It would be great to have an option to use passwordless login as well as password authentication.

Another option if you don't want to change your auth flows that much is that you could enable OTP or passwordless sign in which eseentially use the same authentication flow.

**Comment by arshad-yaseen** [comment]
Hey, Noted! Wait for the passwordless sign-in experience. Thank you Hector! ❤️

**Comment by arshad-yaseen** [comment]
Hey, Noted! Wait for the OTP sign-in experience. Thank you Hector! ❤️
