### ISSUE TITLE
Collapsable Tools Panel

### ISSUE THREAD

**Issue by iamhectorsosa** [arshad-yaseen/markdx#5]
## Feature Request: Collapsable Tools Panel

Calling the [Editor Left Component](https://github.com/arshad-yaseen/markdx/blob/main/components/editor/editor-left.tsx) the Tools Panel.

As a User I think it would bring nice value to have a collapsable tools panel. Notice in the screenshot below I'm using a Macbook Pro and the space seems a bit limited.

Expected behavior: When writing, I would prefer to have as much screen real estate as possible and focus only on the content and the preview. At a point, whenever needed, I can also expand/collapse the tools panel when I need them.

Added bonus, to have the preview panel also collapsable. Again, to focus on the writing the content first.

![image](https://github.com/arshad-yaseen/markdx/assets/77650775/cd6a628b-cdc8-44ab-88b7-b21035a68e5e)

**Comment by arshad-yaseen** [comment]
Sure, i'll try

**Comment by arshad-yaseen** [comment]
Done

**Comment by iamhectorsosa** [comment]
🔥
