### ISSUE TITLE
Editor Resizable Panels 

### ISSUE THREAD

**Issue by iamhectorsosa** [arshad-yaseen/markdx#6]
## Feature Request: Editor Resizable Panels 

It'd be nice to have the editor and preview panel resizable with a handle for ease of use. Sometimes you need to check how to content looks and it is specially useful at limited screen sizes. Again, referencing the screenshot below on a Macbook Pro.

![image](https://github.com/arshad-yaseen/markdx/assets/77650775/cac20314-cdda-4fbd-b2d1-b4107515af40)

**Comment by arshad-yaseen** [comment]
Done

**Comment by arshad-yaseen** [comment]
It is being worked on. This issue closed by my mistake.
