### ISSUE TITLE
TypeError: worldlanguages.map is not a function

### ISSUE THREAD

**Issue by afarhadi99** [arshad-yaseen/markdx#7]
When I try to run the app locally, i get this error

TypeError: worldlanguages.map is not a function

**Comment by arshad-yaseen** [comment]
Have you added rapid api key in .env.local?

**Comment by c-nemo-y** [comment]
It might be that `worldlanguages` is not an array. casting it as array fixed it for me: `Object.values(worldlanguages).map`

**Comment by arshad-yaseen** [comment]
> It might be that `worldlanguages` is not an array. casting it as such fixed it for me: `Object.values(worldlanguages).map`

Yeah, thnx @c-nemo-y

**Comment by arshad-yaseen** [comment]
> It might be that `worldlanguages` is not an array. casting it as such fixed it for me: `Object.values(worldlanguages).map`

Yeah, Just do this.
