### ISSUE TITLE
Broken integration with Github auth

### ISSUE THREAD

**Issue by randallQuickDo** [arshad-yaseen/markdx#8]
I used Github to login and I think the data returns are not mine since this is a new account.

![Capture d’écran (283)](https://github.com/arshad-yaseen/markdx/assets/135260486/0fa1705f-2635-4f43-b1a1-83b1ee98500b)

**Comment by arshad-yaseen** [comment]
Hey, I actually noticed that earlier, and I'm already working on fixing it. To address the issue, could you please sign out quickly? Once you've signed out, please use your email to log in again. This should help resolve the problem. Thank you for your patience!

**Comment by ricardonunez0** [comment]
Those are my notes too hahah from "React Server Components", was wondering what was going on.
